#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         0 #default - 2
bspc config window_gap          12 #default - 12 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

~/.config/bspwm/scripts/fehbg.sh
~/.config/bspwm/scripts/keyboard.sh
setxkbmap -model pc105 -layout us,ua -option grp:alt_shift_toggle
paplay /home/fortis/.config/bspwm/scripts/sounds/zdarova-zaebal.mp3


picom --animations --animation-for-open-window fly-in -b
sudo chmod 666 /dev/ttyUSB0

xsetroot -cursor_name left_ptr
